app/__init__.py
"""
This is the __init__.py script 

It acts as tje glue for the entire flask application 

It essentially formats the app/ folder as a package, making our scripts into moduels 
Giving us the ability to basically import scripts 

It also loads the configurations from the config file, and it initalizes extensions, as well
as registering blueprints (routes) into the application
"""

from flask import Flask ## This class "Flask" let's us create an instance of Flask
from .db import init_app ## This is the function that closes our db connection automatically 
from .routes import main ## we'll create this file later, with reports
## and we'll import blue print here 
## and we do that to register routes into our aplication


def create_app():
    """
    Will be to have it run on our "run.py" to create the app and it running on a development server 
    """
    app = Flask(__name__, template_folder="templates", static_folder ="static")
## The double underscore "name" is a built-in variable to get the name of the current file
## and we're trying to register the template folder and the static folder into out flask app
    app.config.from_object("config.Config")

    init_app(app)

    app.register_blueprint(main)

    return app

app/routes.py
"""
This routes.py script will contain the routes/path for our application
"""

from flask import Blueprint, render_template, request, session, url_for
from .db import query_test
from .login import handle_login
from .register import handle_registration


main = Blueprint("main", __name__)
## initializies a blueprint

@main.route("/")
def index():
    ## we will change this to render html home page later on 
    return render_template("index.html")
    
## Add the route for the login 
@main.route("/login", methods =("GET", "POST")) ##localhost/
def login():
    if request.method == "POST":
        ## Login.py script logic here

        return render_template("login.html")

## adding the register route 
@main.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        ## Call the register.py script logic here
         
        return render_template("register.html")

## Adding the about page route
@main.route("/about")
def about():
    return render_template("about.html")

app/templates/about.html
{% extends "base.html" %}

{% block title %}
About - My Flask App 
{% endblock %}

{% block content %}
    <h2>This is the about page!</h2>
    <a href="{{ url_for('main.index') }}">Go to Home</a>
{% endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Flask App{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/ucnj_style.css') }}">
</head>

<body>
    <header>
        <h1>UCNJ Flask Demo</h1>
    </header>
    <main>
        {% block content %}

        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2025 Union college - Joshua Juarez </p>
    </footer>

    <script src="{{ url_for('static', filename='js/flash.js') }}"></script>
    
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}
Home - My Flask App 
{% endblock %}

{% block content %}
    <h2>Welcome to My Flask App!</h2>
    <a href="{{ url_for('main.about') }}">Go to About Page</a>
{% endblock%}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1.0">
    <title>Login form</title>
    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body{
            min-height: 100vh;
            background: #eee;
            display: flex;
            font-family: sans-serif;
        }
        .container{
            margin: auto;
            width: 500px;
            max-width: 90%;
        }
        .container form{
            width: 100%;
            height: 100%;
            padding: 20px;
            background: white;
            border-radius: 4px;
            box-shadow: 0 8px 16px rgba(0,0,0,.3);
        }
        .container form h1{
            text-align: center;
            margin-bottom: 24px;
            color: #222
        }
        .container form .form-control{
            width: 100%;
            height: 40px;
            background: white;
            border-radius: 4px;
            border: 1px solid silver;
            margin: 10px 0 18px 0;
            padding: 0 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <form action="">
            <h1>Login</h1>
            <div class="form-group">
                <label for="">Email id</label>
                <input type="text" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="">Password</label>
                <input type="password" class="form-control" required>
            </div>
            <input type="Sumbit" class="btn" value="Login">
        </form>
    </div>

</body>
</html>